[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
colored = "*"
llcc_core = { path = "crates/core" }
llcc_error = { path = "crates/error" }
llcc_orchestrator = { path = "crates/orchestrator" }
llcc_proc_macro = { path = "crates/proc_macro" }
llcc_semantics = { path = "crates/semantics" }
num = "*"
quickcheck = "*"
quickcheck_macros = "*"
strum = { version = "*", features = ["derive"] }
uuid = { version = "*", features = ["v4"] }
